"""empty message

Revision ID: 3979b3ebce03
Revises: 1f17d8403f86
Create Date: 2023-02-27 23:15:28.835288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3979b3ebce03'
down_revision = '1f17d8403f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###
