"""empty message

Revision ID: 80240fc6a354
Revises: 105390bca102
Create Date: 2023-04-03 15:21:01.207722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80240fc6a354'
down_revision = '105390bca102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    # ### end Alembic commands ###
